#pragma once

#include <algorithm>
#include <array>
#include <atomic>
#include <bit>
#include <cassert>
#include <chrono>
#include <concepts>
#include <coroutine>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <functional>
#include <limits>
#include <memory>
#include <mutex>
#include <optional>
#include <ranges>
#include <queue>
#include <random>
#include <span>
#include <string>
#include <stdexcept>
#include <vector>

#include <boost/multiprecision/cpp_int.hpp>
#define FMT_HEADER_ONLY
#include <fmt/core.h>
